#pragma once
int screenWidth = 800;
int screenHeight = 400;
float ratio = static_cast<float>(screenHeight) / static_cast<float>(screenWidth);
int location;
unsigned int buffer;
std::string vertexShader;
std::string fragmentShader;
double valueDCX = 0.0;
double valueDCY = 0.0;
float xm = static_cast<float>(valueDCX);
float ym = static_cast<float>(valueDCY);
GLFWwindow* window;
float bgSlotsA = 0.621f;
float bgSlotsB = 0.755f;
float bgSlotsX = -0.24f;
float bgSlotsY = 0.0f;
float buttonA = 0.181f;
float buttonB = 0.177f;
float buttonX = 0.695f;
float buttonY = 0.5809f;
float barrelA = bgSlotsA / 5.0f;
float barrelB = bgSlotsB;
float* barrelsX = new float[5];
float squareA = 0.167927f;
float slotY[5];
int waitLMB = 0;
bool mayPressStart = true;
bool mayPressStop = false;
bool motion = false;
bool speedUpSet[5] = { true };
bool speedUp[5] = { false };
float speedConst = 2.2f;
float speed[5] = { 0.0f };
int randLag[5] = { 0 };
bool slow = false;
bool checkMatch = false;
int counter[5] = { 0 };
int timerStop = 0;
float angle = 0.0f;
float origCenter[2];
bool speedZero = false;
int m = 0;